//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement.Presentation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendence
    {
        public int AttendenceId { get; set; }
        public System.DateTime TodayDate { get; set; }
        public string Attended { get; set; }
        public int StudentId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
